services:
  - type: web
    name: rently-api
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rently-db
          property: connectionString
      - key: CORS_ORIGINS
        value: https://chichari2.github.io,https://*.onrender.com,http://localhost:63342
    healthCheckPath: /items

databases:
  - name: rently-db
    plan: free
